# Generated by Django 5.2.8 on 2026-06-28 00:02

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF"),
                            ("image", "Imagen"),
                            ("text", "Texto"),
                            ("quiz", "Evaluación"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(default="Nuevo contenido", max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=courses.models.content_upload_path,
                    ),
                ),
                ("body", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Contenido",
                "verbose_name_plural": "Contenidos",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Evaluación", max_length=200)),
                ("max_score", models.PositiveIntegerField(default=100)),
                ("min_score", models.PositiveIntegerField(default=60)),
                ("attempts", models.CharField(default="1", max_length=20)),
                ("instructions", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Evaluación de sección",
                "verbose_name_plural": "Evaluaciones de sección",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="courses/covers/"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=1, help_text="Duración del curso en horas"
                    ),
                ),
                ("initial_content", models.TextField(default="Sin contenido inicial")),
                ("objectives", models.TextField(blank=True)),
                ("preview_video", models.URLField(blank=True)),
                ("language", models.CharField(default="Español", max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending", "Pendiente de aprobación"),
                            ("published", "Publicado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="courses.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["-created_at"],
            },
        ),
    ]
