# Generated by Django 5.2.8 on 2026-06-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectioncontent",
            name="label",
            field=models.CharField(default="Contenido", max_length=200),
        ),
    ]
