# Generated by Django 5.2.8 on 2026-06-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_category_id_alter_course_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.PositiveIntegerField(
                default=1, help_text="Duración del curso en horas"
            ),
            preserve_default=False,
        ),
    ]
