# Generated by Django 5.2.8 on 2026-06-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_add_level_duration"),
        ("courses", "0003_alter_category_id_alter_course_id"),
    ]

    operations = []
