# Generated by Django 5.2.8 on 2026-06-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="initial_content",
            field=models.TextField(default="Contenido inicial pendiente"),
            preserve_default=False,
        ),
    ]
