# Generated by Django 5.2.8 on 2026-06-19 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_initial_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(default="Español", max_length=30),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Principiante"),
                    ("intermediate", "Intermedio"),
                    ("advanced", "Avanzado"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="objectives",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="preview_video",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF"),
                            ("image", "Imagen"),
                            ("text", "Texto"),
                            ("quiz", "Evaluación"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="courses.coursesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenido",
                "verbose_name_plural": "Contenidos",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("max_score", models.PositiveIntegerField(default=100)),
                ("min_score", models.PositiveIntegerField(default=60)),
                ("attempts", models.CharField(default="1", max_length=20)),
                ("instructions", models.TextField(blank=True)),
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="courses.coursesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de sección",
                "verbose_name_plural": "Evaluaciones de sección",
            },
        ),
    ]
