# Generated by Django 5.2.8 on 2026-06-19 02:26

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_language_course_level_course_objectives_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectioncontent",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sectioncontent",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=courses.models.content_upload_path
            ),
        ),
    ]
