# Generated by Django 5.2.8 on 2026-06-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_sectioncontent_body_sectioncontent_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/covers/"),
        ),
    ]
