# Generated by Django 5.2.8 on 2026-06-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_merge_20260623_1101"),
        ("courses", "0008_course_cover_image"),
    ]

    operations = []
